services:
  stoneblock4:
    image: SEU_USUARIO_DOCKERHUB/stoneblock4:latest
    container_name: stoneblock4
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FTB"
      FTB_MODPACK_ID: "130"
      MEMORY: "8G"
    volumes:
      - ./data:/data
